name: Checkout
on: [push]

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner
    steps:
      - name: Before checkout action
        run: ls -a
      - name: Checkout Action
        uses: actions/checkout@v4
        with:
          path: /home/runner
      - name: After checkout action
        run: ls -a

  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: |
          ls -a
          env
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout master
      - name: List files after
        run: ls -a
