name: Repository Internal Events
on: [push, pull_request, issues]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print SHA and REF
        run: |
        ls -a
        echo $GITHUB_SHA
        echo $GITHUB_REF
      - uses: actions/checkout@v4